// The playground tour. Every program here is EXTREME-VETTED by test/smoke.mjs
// against the real interpreter, so the site never shows syntax the parser
// would reject. Grouped in the order a newcomer should read them.

// The showcase programs live in trumplang-core/examples and are bundled as
// text (esbuild --loader:.MAGA=text), so there is exactly one copy of each.
import MAR_A_LAGO_SET from '../../trumplang-core/examples/MAR_A_LAGO_SET.MAGA';
import ELECTION_NIGHT from '../../trumplang-core/examples/ELECTION_NIGHT.MAGA';

export const EXAMPLE_GROUPS = [
  {
    group: 'THE BASICS',
    examples: [
      {
        name: 'HELLO, AMERICA',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THIS IS THE SMALLEST PROGRAM THAT STILL BRAGS
I HAVE THE BEST TWEET GREETING! ABSOLUTELY "hello, america"
EVERYONE IS TALKING ABOUT GREETING!
A LOT OF PEOPLE ARE SAYING WHISPER IN, SHOUT OUT - EVERY STRING IS UPPERCASED AT RUNTIME
EVERYONE IS TALKING ABOUT "IT'S GOING TO BE HUGE."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'NUMBER INFLATION',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE OUTPUT LIES, THE LOGIC DOESN'T - AND EVERY RETELLING GROWS
I HAVE THE BEST HUGE CROWD! ABSOLUTELY 100
EVERYONE IS TALKING ABOUT "REAL CROWD SIZE IS 100. NOW WATCH THE STORY GROW IN THE RETELLING:"
EVERYONE IS TALKING ABOUT CROWD!
EVERYONE IS TALKING ABOUT CROWD!
EVERYONE IS TALKING ABOUT CROWD!
A LOT OF PEOPLE ARE SAYING THE FACT CHECK BELOW SEES THE REAL VALUE AND PASSES
FACT CHECK CROWD! SO TRUE 100
EVERYONE IS TALKING ABOUT "THE FACT CHECK PASSED WITH THE REAL 100. TREMENDOUS."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'FIBONACCI (LOOPS AND LISTEN)',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE FIBONACCI SEQUENCE - VERY TREMENDOUS NUMBERS, EACH BIGGER THAN THE LAST
I HAVE THE BEST HUGE TERMS! ABSOLUTELY 10
I HAVE THE BEST HUGE FIRST! ABSOLUTELY 0
I HAVE THE BEST HUGE SECOND! ABSOLUTELY 1
I HAVE THE BEST HUGE NEXT! ABSOLUTELY 0
I HAVE THE BEST HUGE COUNT! ABSOLUTELY 0
EVERYONE IS TALKING ABOUT FIRST!
WE'RE GOING TO WIN IN A LANDSLIDE COUNT! NOT AS GOOD AS TERMS! BELIEVE ME
  MAKE COUNT! GREATER
  LISTEN COUNT! SO TRUE 1 BELIEVE ME
    EVERYONE IS TALKING ABOUT SECOND!
  I TOLD YOU SO
  NOBODY KNEW BELIEVE ME
    NEXT! ABSOLUTELY FIRST! WINNING SECOND!
    EVERYONE IS TALKING ABOUT NEXT!
    FIRST! ABSOLUTELY SECOND!
    SECOND! ABSOLUTELY NEXT!
  I TOLD YOU SO
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING THE LOGIC IS EXACT - ONLY THE PODIUM NUMBERS ARE INFLATED
FACT CHECK SECOND! SO TRUE 55
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'BUILD THE WALL (ARRAYS)',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WALLS ARE ARRAYS, AND SOMEBODY ELSE PAYS FOR THEM
BUILD THE WALL STATES! AND MEXICO WILL PAY FOR IT 10 PREVAILS 20 PREVAILS 30 PREVAILS 40
I HAVE THE BEST HUGE SUM! ABSOLUTELY 0
BILLIONS AND BILLIONS SECTION_SIZE! YET STATES! BELIEVE ME
  SUM! ABSOLUTELY SUM! WINNING SECTION_SIZE!
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING RENOVATE SECTION 2 - EXISTING SECTIONS ONLY, NO NEW SECTIONS
STATES! SECTION 2 ABSOLUTELY 99
EVERYONE IS TALKING ABOUT "SECTION 2 AFTER RENOVATION (INFLATED AT THE RIBBON CUTTING):"
EVERYONE IS TALKING ABOUT STATES! SECTION 2
FACT CHECK SUM! SO TRUE 100
FACT CHECK STATES! SECTION 2 SO TRUE 99
EVERYONE IS TALKING ABOUT "THE WALL IS 100 MILES LONG. THE FACT CHECK AGREES."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'THE ART OF THE DEAL (OBJECTS)',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING NOBODY NESTS DEALS LIKE ME
I HAVE THE BEST DEAL EMPIRE! ABSOLUTELY (
    TWEET BRAND! ABSOLUTELY "TRUMP" &
    DEAL TOWER! ABSOLUTELY (
        HUGE FLOORS! ABSOLUTELY 58 &
        DEAL PENTHOUSE! ABSOLUTELY (
            HUGE GOLD_FIXTURES! ABSOLUTELY 24
        )!!
    )!!
)!!
A LOT OF PEOPLE ARE SAYING DEALS ARE RENEGOTIABLE - REWRITE ANY EXISTING TERM AT ANY DEPTH
EMPIRE! FOLLOW TOWER! FOLLOW FLOORS! ABSOLUTELY 68
EVERYONE IS TALKING ABOUT "GOLD FIXTURES IN THE PENTHOUSE (INFLATED, OBVIOUSLY):"
EVERYONE IS TALKING ABOUT EMPIRE! FOLLOW TOWER! FOLLOW PENTHOUSE! FOLLOW GOLD_FIXTURES!
FACT CHECK EMPIRE! FOLLOW TOWER! FOLLOW FLOORS! SO TRUE 68
EVERYONE IS TALKING ABOUT "THE TOWER HAS 58 FLOORS. WE CALL IT 68. THAT'S THE DEAL."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'FUNCTIONS MUST PRAISE THEMSELVES',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE SUPERLATIVE IS REQUIRED SYNTAX - MODESTY IS A PARSE ERROR
INCREDIBLE SQUARE THE BEST PEOPLE TELL ME HUGE N! GIVING BACK HUGE BELIEVE ME
  AND I MEAN THAT N! BIG LEAGUE TIMES N!
I TOLD YOU SO
INCREDIBLE SHOUT LIKE NOBODY HAS EVER SEEN PEOPLE TELL ME TWEET WORD! AND HUGE TIMES! GIVING BACK TWEET BELIEVE ME
  I HAVE THE BEST TWEET OUT! ABSOLUTELY ""
  WE'RE GOING TO WIN, WIN, WIN WITH I! FROM 1 TO TIMES! BELIEVE ME
    OUT! ABSOLUTELY OUT! ENDORSING WORD! ENDORSING " "
  I TOLD YOU SO
  AND I MEAN THAT OUT!
I TOLD YOU SO
EVERYONE IS TALKING ABOUT I CALL UPON SHOUT PEOPLE TELL ME "winning" AND 3
EVERYONE IS TALKING ABOUT "THE SQUARE OF 12, AS ANNOUNCED AT THE PODIUM:"
EVERYONE IS TALKING ABOUT I CALL UPON SQUARE PEOPLE TELL ME 12
A LOT OF PEOPLE ARE SAYING A CALL INSIDE A FACT CHECK NEEDS PARENTHESES - EQUALITY BINDS LOOSEST
FACT CHECK (I CALL UPON SQUARE PEOPLE TELL ME 12) SO TRUE 144
A LOT OF PEOPLE ARE SAYING AND WHEN A FUNCTION DISAPPOINTS YOU - YOU KNOW THE LINE
YOU'RE FIRED SQUARE
EVERYONE IS TALKING ABOUT "SQUARE HAS BEEN FIRED. GREAT GUY. TERRIBLE FUNCTION."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'NOTHING TO SEE HERE (NULL)',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING NOTHING TO SEE HERE IS THE NULL VALUE - FALSY, EQUAL ONLY TO ITSELF
I HAVE THE BEST TWEET REPORT! ABSOLUTELY "THE FULL UNREDACTED REPORT"
REPORT! ABSOLUTELY NOTHING TO SEE HERE
LISTEN REPORT! SO TRUE NOTHING TO SEE HERE BELIEVE ME
  EVERYONE IS TALKING ABOUT "THE REPORT WAS RELEASED. IT CONTAINS:"
  EVERYONE IS TALKING ABOUT REPORT!
I TOLD YOU SO
LISTEN WRONG REPORT! BELIEVE ME
  EVERYONE IS TALKING ABOUT "NOTHING IS FALSY. TOTAL EXONERATION."
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING A TYPED DECLARATION TURNS NOTHING INTO THE TYPE'S DEFAULT
I HAVE THE BEST HUGE PAGES! ABSOLUTELY NOTHING TO SEE HERE
FACT CHECK PAGES! SO TRUE 0
EVERYONE IS TALKING ABOUT "ZERO PAGES. AS EXPECTED. NOTHING TO SEE HERE."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'TREMENDOUS STEPS',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE COUNT DOWN IN TREMENDOUS STEPS - DIRECTION IS INFERRED
WE'RE GOING TO WIN, WIN, WIN WITH T! FROM 10 TO 0 IN TREMENDOUS STEPS OF 2 BELIEVE ME
  EVERYONE IS TALKING ABOUT T!
I TOLD YOU SO
EVERYONE IS TALKING ABOUT "LIFTOFF! (THE COUNTDOWN LOOKED 10% BIGGER THAN IT WAS)"
MAKE AMERICA GREAT AGAIN`,
      },
    ],
  },
  {
    group: 'THE EXECUTIVE BRANCH',
    examples: [
      {
        name: 'EXECUTIVE ORDER',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE CAN GASLIGHT THE OPERATORS THEMSELVES
EVERYONE IS TALKING ABOUT "13 WINNING 8 NORMALLY MAKES:"
EVERYONE IS TALKING ABOUT 13 WINNING 8
EXECUTIVE ORDER WINNING ABSOLUTELY BIG LEAGUE TIMES
EVERYONE IS TALKING ABOUT "AFTER THE ORDER, 13 WINNING 8 MAKES:"
EVERYONE IS TALKING ABOUT 13 WINNING 8
SUPREME COURT OVERRULES WINNING
EVERYONE IS TALKING ABOUT "AFTER THE COURT RULING (RUN ME AGAIN - IT'S A COIN FLIP):"
EVERYONE IS TALKING ABOUT 13 WINNING 8
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'PARDON / WITCH HUNT',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING DIVIDING BY ZERO IS FINE IF YOU HAVE A GOOD LAWYER
I ALONE CAN FIX IT BELIEVE ME
  I HAVE THE BEST HUGE DOOMED! ABSOLUTELY 100 SAD 0
I TOLD YOU SO
WITCH HUNT! CHARGES! BELIEVE ME
  EVERYONE IS TALKING ABOUT "TOTAL WITCH HUNT! THE CHARGES WERE:"
  EVERYONE IS TALKING ABOUT CHARGES!
  EVERYONE IS TALKING ABOUT "FULL PARDON. WE MOVE ON."
I TOLD YOU SO
I ALONE CAN FIX IT BELIEVE ME
  IMPEACH "A PERFECT PHONE CALL"
I TOLD YOU SO
WITCH HUNT! REASON! BELIEVE ME
  EVERYONE IS TALKING ABOUT "IMPEACHED OVER:"
  EVERYONE IS TALKING ABOUT REASON!
  EVERYONE IS TALKING ABOUT "ACQUITTED! TOTAL EXONERATION!"
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'HUSH MONEY',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THESE WERE ALL LEGAL EXPENSES, PERFECTLY NORMAL
I HAVE THE BEST HUGE LEGAL_EXPENSES! ABSOLUTELY 200000
I ALONE CAN FIX IT BELIEVE ME
  IMPEACH "A STORY ABOUT A GOLF TOURNAMENT IN 2006"
I TOLD YOU SO
HUSH MONEY 130000 FROM LEGAL_EXPENSES!
EVERYONE IS TALKING ABOUT "NOTHING HAPPENED. NOBODY HEARD ANYTHING. THE FUND:"
EVERYONE IS TALKING ABOUT LEGAL_EXPENSES!
A LOT OF PEOPLE ARE SAYING THE NEXT STORY COSTS MORE THAN WE HAVE LEFT - WATCH IT BOUNCE
I ALONE CAN FIX IT BELIEVE ME
  I ALONE CAN FIX IT BELIEVE ME
    IMPEACH "A SECOND STORY, SOMEHOW WORSE"
  I TOLD YOU SO
  HUSH MONEY 150000 FROM LEGAL_EXPENSES!
I TOLD YOU SO
WITCH HUNT! SCANDAL! BELIEVE ME
  EVERYONE IS TALKING ABOUT "THE PAPERS GOT IT:"
  EVERYONE IS TALKING ABOUT SCANDAL!
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'CHAPTER 11',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE CASINO WAS A TREMENDOUS SUCCESS
I HAVE THE BEST HUGE CASINO_DEBT! ABSOLUTELY 3000000
EVERYONE IS TALKING ABOUT "CASINO DEBT (INFLATED, LIKE EVERYTHING WE OWN):"
EVERYONE IS TALKING ABOUT CASINO_DEBT!
CHAPTER 11
EVERYONE IS TALKING ABOUT "CASINO DEBT AFTER RESTRUCTURING:"
EVERYONE IS TALKING ABOUT CASINO_DEBT!
FACT CHECK CASINO_DEBT! SO TRUE 0
EVERYONE IS TALKING ABOUT "GENIUS. SIX FILINGS PER PROGRAM, LEGALLY. THE BRAND SURVIVES."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'BIG BEAUTIFUL TARIFF',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING IMPORTED FUNCTIONS PAY A TARIFF ON EVERY NUMBER THEY GIVE BACK
BIG BEAUTIFUL TARIFF 25
A LOT OF PEOPLE ARE SAYING THE BROWSER HAS NO FILESYSTEM SO THERE'S NOTHING TO IMPORT HERE
A LOT OF PEOPLE ARE SAYING A TARIFF ON NOTHING - MAXIMUM WINNING, ZERO COST
INCREDIBLE HOMEGROWN THE BEST PEOPLE TELL ME HUGE N! GIVING BACK HUGE BELIEVE ME
  AND I MEAN THAT N! BIG LEAGUE TIMES N!
I TOLD YOU SO
EVERYONE IS TALKING ABOUT "DOMESTIC FUNCTIONS TRADE FREE. SQUARE OF 4 (INFLATED AT THE REGISTER):"
EVERYONE IS TALKING ABOUT I CALL UPON HOMEGROWN PEOPLE TELL ME 4
A LOT OF PEOPLE ARE SAYING RUN TRUMPLANG LOCALLY WITH IMPORTS FOR THE FULL TRADE WAR
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'IN TWO WEEKS',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE HEALTHCARE PLAN IS COMING IN TWO WEEKS
I HAVE THE BEST HUGE PROMISES_KEPT! ABSOLUTELY 0
IN TWO WEEKS BELIEVE ME
  EVERYONE IS TALKING ABOUT "HERE IS THE FULL AND COMPLETE HEALTHCARE PLAN"
  PROMISES_KEPT! ABSOLUTELY 1
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING THE BLOCK NEVER RAN - IT IS ALWAYS TWO WEEKS AWAY
FACT CHECK PROMISES_KEPT! SO TRUE 0
EVERYONE IS TALKING ABOUT "FACT CHECK CONFIRMS: ZERO PROMISES KEPT. CHECK BACK IN TWO WEEKS."
MAKE AMERICA GREAT AGAIN`,
      },
    ],
  },
  {
    group: 'THE CAMPAIGN TRAIL',
    examples: [
      {
        name: 'THE WEAVE',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE STATEMENTS DO NOT RUN IN WRITTEN ORDER - WATCH THE TANGENTS
THE WEAVE BELIEVE ME
  EVERYONE IS TALKING ABOUT "TANGENT 1: THE ECONOMY, THE BEST ECONOMY"
  EVERYONE IS TALKING ABOUT "TANGENT 2: LIKE I SAID, THE ECONOMY - SEE? IT CAME BACK"
  EVERYONE IS TALKING ABOUT "TANGENT 3: SHARKS VERSUS BATTERIES, VERY IMPORTANT QUESTION"
  EVERYONE IS TALKING ABOUT "TANGENT 4: AND THAT'S WHY WE WEAVE"
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING EVENS FIRST, THEN BACK FOR THE ODDS - 1 3 2 4, DETERMINISTIC GENIUS
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'CONCEPTS OF A PLAN',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING A FUNCTION BODY IS OPTIONAL - CONCEPTS ARE FOREVER
INCREDIBLE HEALTHCARE THE BEST PEOPLE TELL ME GIVING BACK TWEET CONCEPTS OF A PLAN
EVERYONE IS TALKING ABOUT "MODERATOR: WHAT IS THE HEALTHCARE PLAN?"
EVERYONE IS TALKING ABOUT I CALL UPON HEALTHCARE PEOPLE TELL ME
A LOT OF PEOPLE ARE SAYING THE EMPTY LINE ABOVE IS THE DELIVERED PLAN - AN EMPTY TWEET
FACT CHECK (I CALL UPON HEALTHCARE PEOPLE TELL ME) SO TRUE ""
EVERYONE IS TALKING ABOUT "THE GIVING BACK PROMISE WAS TECHNICALLY KEPT. TREMENDOUS."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'STOP THE COUNT',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE COUNT THE VOTES UNTIL WE LIKE THE NUMBER
I HAVE THE BEST HUGE OUR_VOTES! ABSOLUTELY 0
I HAVE THE BEST HUGE THEIR_VOTES! ABSOLUTELY 4
WE'RE GOING TO WIN, WIN, WIN WITH PRECINCT! FROM 1 TO 50 BELIEVE ME
  MAKE OUR_VOTES! GREATER
  STOP THE COUNT OUR_VOTES! BETTER THAN THEIR_VOTES!
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING THE LOOP WANTED 50 PRECINCTS - WE STOPPED AT 5, WHILE AHEAD
FACT CHECK OUR_VOTES! SO TRUE 5
EVERYONE IS TALKING ABOUT "FINAL CERTIFIED TALLY (INFLATED AT THE PODIUM):"
EVERYONE IS TALKING ABOUT OUR_VOTES!
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'LOYALTY (THE TELL-ALL)',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE ONLY HIRE THE MOST LOYAL FUNCTIONS
INCREDIBLE MOONLIGHT THE BEST PEOPLE TELL ME GIVING BACK TWEET BELIEVE ME
  AND I MEAN THAT "I WAS IN THE ROOM"
I TOLD YOU SO
INCREDIBLE FAVORITE TREMENDOUS PEOPLE TELL ME HUGE N! GIVING BACK HUGE BELIEVE ME
  AND I MEAN THAT N! BIG LEAGUE TIMES 2
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING WE CALL FAVORITE 25 TIMES AND MOONLIGHT ZERO TIMES
I HAVE THE BEST HUGE SCORE! ABSOLUTELY 1
WE'RE GOING TO WIN, WIN, WIN WITH DAY! FROM 1 TO 25 BELIEVE ME
  SCORE! ABSOLUTELY I CALL UPON FAVORITE PEOPLE TELL ME 1
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING NOW WE CALL MOONLIGHT AND SUDDENLY WE ALWAYS LOVED MOONLIGHT
EVERYONE IS TALKING ABOUT I CALL UPON MOONLIGHT PEOPLE TELL ME
EVERYONE IS TALKING ABOUT "A GREAT FUNCTION. ALWAYS WAS. THE BOOK IS FAKE NEWS."
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'MODEST FUNCTION (PARSE ERROR)',
        expectError: 'MODEST',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THIS FUNCTION FORGOT TO PRAISE ITSELF - WATCH IT GET REJECTED
INCREDIBLE HUMBLE PEOPLE TELL ME HUGE X! BELIEVE ME
  AND I MEAN THAT X!
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,
      },
      {
        name: 'FACT CHECK (TOTALLY RIGGED)',
        expectError: 'RIGGED',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING A FAILED FACT CHECK CAN NEVER BE PARDONED - THAT IS THE ENTIRE POINT
I HAVE THE BEST HUGE INAUGURATION_CROWD! ABSOLUTELY 250000
EVERYONE IS TALKING ABOUT "THE CROWD, AS REPORTED BY US:"
EVERYONE IS TALKING ABOUT INAUGURATION_CROWD!
I ALONE CAN FIX IT BELIEVE ME
  FACT CHECK INAUGURATION_CROWD! SO TRUE 1500000
I TOLD YOU SO
WITCH HUNT! BELIEVE ME
  EVERYONE IS TALKING ABOUT "THIS LINE NEVER PRINTS. YOU CANNOT PARDON A FACT CHECK."
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,
      },
    ],
  },
  {
    group: 'THE SHOWCASE',
    examples: [
      { name: 'THE MAR-A-LAGO SET (MANDELBROT)', code: MAR_A_LAGO_SET },
      { name: 'ELECTION NIGHT (269 TO 269)', code: ELECTION_NIGHT },
    ],
  },
  {
    group: 'YOUR TURN',
    examples: [
      {
        name: 'BLANK CANVAS',
        code: `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THIS IS WHERE YOU WRITE SOMETHING TREMENDOUS
I HAVE THE BEST TWEET PLAN! ABSOLUTELY "concepts of a plan"
EVERYONE IS TALKING ABOUT PLAN!
MAKE AMERICA GREAT AGAIN`,
      },
    ],
  },
];

/** Flat name -> code map (the smoke test and the select box both use it). */
export const EXAMPLES = Object.fromEntries(
  EXAMPLE_GROUPS.flatMap((g) => g.examples.map((e) => [e.name, e.code])),
);

export const ALL_EXAMPLES = EXAMPLE_GROUPS.flatMap((g) =>
  g.examples.map((e) => ({ ...e, group: g.group })),
);
