// Trumplang web playground - runs the REAL ANTLR4-based interpreter in the
// browser. The output lies by 10%, the logic doesn't. That's the language,
// not a bug in this playground.
import { TrumplangInterpreter } from '../../trumplang-core/src/interpreter/index.js';

const EXAMPLES = {
  'NUMBER INFLATION': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE OUTPUT LIES, THE LOGIC DOESN'T - AND EVERY RETELLING GROWS
I HAVE THE BEST HUGE CROWD! ABSOLUTELY 100
EVERYONE IS TALKING ABOUT "REAL CROWD SIZE IS 100. NOW WATCH THE STORY GROW IN THE RETELLING:"
EVERYONE IS TALKING ABOUT CROWD!
EVERYONE IS TALKING ABOUT CROWD!
EVERYONE IS TALKING ABOUT CROWD!
A LOT OF PEOPLE ARE SAYING THE FACT CHECK BELOW SEES THE REAL VALUE AND PASSES
FACT CHECK CROWD! SO TRUE 100
EVERYONE IS TALKING ABOUT "THE FACT CHECK PASSED WITH THE REAL 100. TREMENDOUS."
MAKE AMERICA GREAT AGAIN`,

  'EXECUTIVE ORDER': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE CAN GASLIGHT THE OPERATORS THEMSELVES
EVERYONE IS TALKING ABOUT "13 WINNING 8 NORMALLY MAKES:"
EVERYONE IS TALKING ABOUT 13 WINNING 8
EXECUTIVE ORDER WINNING ABSOLUTELY BIG LEAGUE TIMES
EVERYONE IS TALKING ABOUT "AFTER THE ORDER, 13 WINNING 8 MAKES:"
EVERYONE IS TALKING ABOUT 13 WINNING 8
SUPREME COURT OVERRULES WINNING
EVERYONE IS TALKING ABOUT "AFTER THE COURT RULING (RUN ME AGAIN - IT'S A COIN FLIP):"
EVERYONE IS TALKING ABOUT 13 WINNING 8
MAKE AMERICA GREAT AGAIN`,

  'PARDON / WITCH HUNT': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING DIVIDING BY ZERO IS FINE IF YOU HAVE A GOOD LAWYER
I ALONE CAN FIX IT BELIEVE ME
  I HAVE THE BEST HUGE DOOMED! ABSOLUTELY 100 SAD 0
I TOLD YOU SO
WITCH HUNT! CHARGES! BELIEVE ME
  EVERYONE IS TALKING ABOUT "TOTAL WITCH HUNT! THE CHARGES WERE:"
  EVERYONE IS TALKING ABOUT CHARGES!
  EVERYONE IS TALKING ABOUT "FULL PARDON. WE MOVE ON."
I TOLD YOU SO
I ALONE CAN FIX IT BELIEVE ME
  IMPEACH "A PERFECT PHONE CALL"
I TOLD YOU SO
WITCH HUNT! REASON! BELIEVE ME
  EVERYONE IS TALKING ABOUT "IMPEACHED OVER:"
  EVERYONE IS TALKING ABOUT REASON!
  EVERYONE IS TALKING ABOUT "ACQUITTED! TOTAL EXONERATION!"
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,

  'NESTED DEALS': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING NOBODY NESTS DEALS LIKE ME
I HAVE THE BEST DEAL EMPIRE! ABSOLUTELY (
    TWEET BRAND! ABSOLUTELY "TRUMP" &
    DEAL TOWER! ABSOLUTELY (
        HUGE FLOORS! ABSOLUTELY 58 &
        DEAL PENTHOUSE! ABSOLUTELY (
            HUGE GOLD_FIXTURES! ABSOLUTELY 24
        )!!
    )!!
)!!
EVERYONE IS TALKING ABOUT "GOLD FIXTURES IN THE PENTHOUSE (INFLATED, OBVIOUSLY):"
EVERYONE IS TALKING ABOUT EMPIRE! FOLLOW TOWER! FOLLOW PENTHOUSE! FOLLOW GOLD_FIXTURES!
MAKE AMERICA GREAT AGAIN`,

  'TREMENDOUS STEPS': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE COUNT DOWN IN TREMENDOUS STEPS
WE'RE GOING TO WIN, WIN, WIN WITH T! FROM 10 TO 0 IN TREMENDOUS STEPS OF 2 BELIEVE ME
  EVERYONE IS TALKING ABOUT T!
I TOLD YOU SO
EVERYONE IS TALKING ABOUT "LIFTOFF! (THE COUNTDOWN LOOKED 10% BIGGER THAN IT WAS)"
MAKE AMERICA GREAT AGAIN`,

  'THE WEAVE': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE STATEMENTS DO NOT RUN IN WRITTEN ORDER - WATCH THE TANGENTS
THE WEAVE BELIEVE ME
  EVERYONE IS TALKING ABOUT "TANGENT 1: THE ECONOMY, THE BEST ECONOMY"
  EVERYONE IS TALKING ABOUT "TANGENT 2: LIKE I SAID, THE ECONOMY - SEE? IT CAME BACK"
  EVERYONE IS TALKING ABOUT "TANGENT 3: SHARKS VERSUS BATTERIES, VERY IMPORTANT QUESTION"
  EVERYONE IS TALKING ABOUT "TANGENT 4: AND THAT'S WHY WE WEAVE"
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING EVENS FIRST, THEN BACK FOR THE ODDS - 1 3 2 4, DETERMINISTIC GENIUS
MAKE AMERICA GREAT AGAIN`,

  'CONCEPTS OF A PLAN': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING A FUNCTION BODY IS OPTIONAL - CONCEPTS ARE FOREVER
INCREDIBLE HEALTHCARE THE BEST PEOPLE TELL ME GIVING BACK TWEET CONCEPTS OF A PLAN
EVERYONE IS TALKING ABOUT "MODERATOR: WHAT IS THE HEALTHCARE PLAN?"
EVERYONE IS TALKING ABOUT I CALL UPON HEALTHCARE PEOPLE TELL ME
A LOT OF PEOPLE ARE SAYING THE EMPTY LINE ABOVE IS THE DELIVERED PLAN - AN EMPTY TWEET
FACT CHECK (I CALL UPON HEALTHCARE PEOPLE TELL ME) SO TRUE ""
EVERYONE IS TALKING ABOUT "THE GIVING BACK PROMISE WAS TECHNICALLY KEPT. TREMENDOUS."
MAKE AMERICA GREAT AGAIN`,

  'IN TWO WEEKS': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE HEALTHCARE PLAN IS COMING IN TWO WEEKS
I HAVE THE BEST HUGE PROMISES_KEPT! ABSOLUTELY 0
IN TWO WEEKS BELIEVE ME
  EVERYONE IS TALKING ABOUT "HERE IS THE FULL AND COMPLETE HEALTHCARE PLAN"
  PROMISES_KEPT! ABSOLUTELY 1
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING THE BLOCK NEVER RAN - IT IS ALWAYS TWO WEEKS AWAY
FACT CHECK PROMISES_KEPT! SO TRUE 0
EVERYONE IS TALKING ABOUT "FACT CHECK CONFIRMS: ZERO PROMISES KEPT. CHECK BACK IN TWO WEEKS."
MAKE AMERICA GREAT AGAIN`,

  'BIG BEAUTIFUL TARIFF': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING IMPORTED FUNCTIONS PAY A TARIFF ON EVERY NUMBER THEY GIVE BACK
BIG BEAUTIFUL TARIFF 25
A LOT OF PEOPLE ARE SAYING THE BROWSER HAS NO FILESYSTEM SO THERE'S NOTHING TO IMPORT HERE
A LOT OF PEOPLE ARE SAYING A TARIFF ON NOTHING - MAXIMUM WINNING, ZERO COST
INCREDIBLE HOMEGROWN THE BEST PEOPLE TELL ME HUGE N! GIVING BACK HUGE BELIEVE ME
  AND I MEAN THAT N! BIG LEAGUE TIMES N!
I TOLD YOU SO
EVERYONE IS TALKING ABOUT "DOMESTIC FUNCTIONS TRADE FREE. SQUARE OF 4 (INFLATED AT THE REGISTER):"
EVERYONE IS TALKING ABOUT I CALL UPON HOMEGROWN PEOPLE TELL ME 4
A LOT OF PEOPLE ARE SAYING RUN TRUMPLANG LOCALLY WITH IMPORTS FOR THE FULL TRADE WAR
MAKE AMERICA GREAT AGAIN`,

  'STOP THE COUNT': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE COUNT THE VOTES UNTIL WE LIKE THE NUMBER
I HAVE THE BEST HUGE OUR_VOTES! ABSOLUTELY 0
I HAVE THE BEST HUGE THEIR_VOTES! ABSOLUTELY 4
WE'RE GOING TO WIN, WIN, WIN WITH PRECINCT! FROM 1 TO 50 BELIEVE ME
  MAKE OUR_VOTES! GREATER
  STOP THE COUNT OUR_VOTES! BETTER THAN THEIR_VOTES!
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING THE LOOP WANTED 50 PRECINCTS - WE STOPPED AT 5, WHILE AHEAD
FACT CHECK OUR_VOTES! SO TRUE 5
EVERYONE IS TALKING ABOUT "FINAL CERTIFIED TALLY (INFLATED AT THE PODIUM):"
EVERYONE IS TALKING ABOUT OUR_VOTES!
MAKE AMERICA GREAT AGAIN`,

  'CHAPTER 11': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THE CASINO WAS A TREMENDOUS SUCCESS
I HAVE THE BEST HUGE CASINO_DEBT! ABSOLUTELY 3000000
EVERYONE IS TALKING ABOUT "CASINO DEBT (INFLATED, LIKE EVERYTHING WE OWN):"
EVERYONE IS TALKING ABOUT CASINO_DEBT!
CHAPTER 11
EVERYONE IS TALKING ABOUT "CASINO DEBT AFTER RESTRUCTURING:"
EVERYONE IS TALKING ABOUT CASINO_DEBT!
FACT CHECK CASINO_DEBT! SO TRUE 0
EVERYONE IS TALKING ABOUT "GENIUS. SIX FILINGS PER PROGRAM, LEGALLY. THE BRAND SURVIVES."
MAKE AMERICA GREAT AGAIN`,

  'HUSH MONEY': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THESE WERE ALL LEGAL EXPENSES, PERFECTLY NORMAL
I HAVE THE BEST HUGE LEGAL_EXPENSES! ABSOLUTELY 200000
I ALONE CAN FIX IT BELIEVE ME
  IMPEACH "A STORY ABOUT A GOLF TOURNAMENT IN 2006"
I TOLD YOU SO
HUSH MONEY 130000 FROM LEGAL_EXPENSES!
EVERYONE IS TALKING ABOUT "NOTHING HAPPENED. NOBODY HEARD ANYTHING. THE FUND:"
EVERYONE IS TALKING ABOUT LEGAL_EXPENSES!
A LOT OF PEOPLE ARE SAYING THE NEXT STORY COSTS MORE THAN WE HAVE LEFT - WATCH IT BOUNCE
I ALONE CAN FIX IT BELIEVE ME
  I ALONE CAN FIX IT BELIEVE ME
    IMPEACH "A SECOND STORY, SOMEHOW WORSE"
  I TOLD YOU SO
  HUSH MONEY 150000 FROM LEGAL_EXPENSES!
I TOLD YOU SO
WITCH HUNT! SCANDAL! BELIEVE ME
  EVERYONE IS TALKING ABOUT "THE PAPERS GOT IT:"
  EVERYONE IS TALKING ABOUT SCANDAL!
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,

  'LOYALTY (THE TELL-ALL)': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING WE ONLY HIRE THE MOST LOYAL FUNCTIONS
INCREDIBLE MOONLIGHT THE BEST PEOPLE TELL ME GIVING BACK TWEET BELIEVE ME
  AND I MEAN THAT "I WAS IN THE ROOM"
I TOLD YOU SO
INCREDIBLE FAVORITE TREMENDOUS PEOPLE TELL ME HUGE N! GIVING BACK HUGE BELIEVE ME
  AND I MEAN THAT N! BIG LEAGUE TIMES 2
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING WE CALL FAVORITE 25 TIMES AND MOONLIGHT ZERO TIMES
I HAVE THE BEST HUGE SCORE! ABSOLUTELY 1
WE'RE GOING TO WIN, WIN, WIN WITH DAY! FROM 1 TO 25 BELIEVE ME
  SCORE! ABSOLUTELY I CALL UPON FAVORITE PEOPLE TELL ME 1
I TOLD YOU SO
A LOT OF PEOPLE ARE SAYING NOW WE CALL MOONLIGHT AND SUDDENLY WE ALWAYS LOVED MOONLIGHT
EVERYONE IS TALKING ABOUT I CALL UPON MOONLIGHT PEOPLE TELL ME
EVERYONE IS TALKING ABOUT "A GREAT FUNCTION. ALWAYS WAS. THE BOOK IS FAKE NEWS."
MAKE AMERICA GREAT AGAIN`,

  'MODEST FUNCTION (PARSE ERROR)': `THE TIME FOR EMPTY TALK IS OVER!!!
A LOT OF PEOPLE ARE SAYING THIS FUNCTION FORGOT TO PRAISE ITSELF - WATCH IT GET REJECTED
INCREDIBLE HUMBLE PEOPLE TELL ME HUGE X! BELIEVE ME
  AND I MEAN THAT X!
I TOLD YOU SO
MAKE AMERICA GREAT AGAIN`,
};

export async function runTrumplang(source) {
  const captured = [];
  const origLog = console.log;
  const origErr = console.error;
  console.log = (...args) => captured.push(args.join(' '));
  console.error = () => {}; // the interpreter re-throws; we surface the error ourselves
  try {
    const interpreter = new TrumplangInterpreter();
    const result = interpreter.interpret(source);
    if (result) captured.push(String(result));
    return { ok: true, output: captured.join('\n') };
  } catch (error) {
    return {
      ok: false,
      output: captured.join('\n'),
      error: String(error && error.message ? error.message : error),
    };
  } finally {
    console.log = origLog;
    console.error = origErr;
  }
}

export { EXAMPLES };

// UI wiring - only in the browser (the smoke test imports this module in Node)
if (typeof document !== 'undefined') {
  const editor = document.getElementById('editor');
  const output = document.getElementById('output');
  const runButton = document.getElementById('run');
  const exampleSelect = document.getElementById('examples');

  for (const name of Object.keys(EXAMPLES)) {
    const option = document.createElement('option');
    option.value = name;
    option.textContent = name;
    exampleSelect.appendChild(option);
  }

  const loadExample = (name) => {
    editor.value = EXAMPLES[name];
    output.textContent = 'PRESS "MAKE IT RUN" TO SEE TREMENDOUS RESULTS.';
    output.className = '';
  };

  exampleSelect.addEventListener('change', () => loadExample(exampleSelect.value));
  loadExample(Object.keys(EXAMPLES)[0]);

  runButton.addEventListener('click', async () => {
    output.textContent = 'RUNNING. THE BEST EXECUTION. HOLD ON...';
    output.className = '';
    const result = await runTrumplang(editor.value);
    if (result.ok) {
      output.textContent = result.output || '(NO OUTPUT. VERY QUIET PROGRAM. SUSPICIOUS!)';
      output.className = 'ok';
    } else {
      output.textContent =
        (result.output ? result.output + '\n\n' : '') +
        'THIS CODE IS A DISASTER! VERY SAD CODE!\n' +
        result.error;
      output.className = 'sad';
    }
  });
}
